# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
steps:
- id: 'test'
  name: maven:3.9.5-eclipse-temurin-21
  entrypoint: mvn
  volumes:
  - name: 'maven-repository'
    path: '/root/.m2'
  args: ["verify"]
- id: 'build-project'
  name: maven:3.9.5-eclipse-temurin-21
  entrypoint: bash
  args:
  - '-c'
  - |
    # bash <(curl -sL https://get.graalvm.org/jdk) graalvm-ce-java17-22.3.1
    # printenv
    # export JAVA_HOME="/workspace/graalvm-ce-java17-22.3.1"
    # gu install native-image
    wget https://download.oracle.com/graalvm/21/archive/graalvm-jdk-21_linux-x64_bin.tar.gz
    tar -xzf graalvm-jdk-21_linux-x64_bin.tar.gz

    export JAVA_HOME=graalvm-jdk-21+35.1 
    mvn spring-boot:build-image  -DskipTests -Pnative -Dspring-boot.build-image.imageName=quotes-native
  volumes:
  - name: 'maven-repository'
    path: '/root/.m2'
- name: gcr.io/cloud-builders/docker
  args: ["tag", "quotes-native", "gcr.io/$PROJECT_ID/quotes-native"]
  # tag then store image in registry
- id: 'tag-image'
  name: gcr.io/cloud-builders/docker
  args: ["tag", "quotes-native", "gcr.io/$PROJECT_ID/quotes-native"]
  # Push the container image to Artifact Registry
- id: 'store-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/quotes-native']
images: ["gcr.io/$PROJECT_ID/quotes-native"]
