steps:
  # Step 1: Clone the GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/ypenn21/serverless-production-readiness-java-gcp.git']

  # Step 2: Build the Docker image with the Java artifact
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'sessions/next24/books-genai-vertex-springai'
    args: ['run', '--rm', '-v', '/workspace:/workspace', '-w', '/workspace/sessions/next24/books-genai-vertex-springai', 'oracle/graalvm-ce:21.0.2-java11', './mvnw', 'spring-boot:build-image', '-DskipTests', '-Dspring-boot.build-image.imageName=books-genai-jit']

  # Step 3: Tag the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'books-genai-jit', 'gcr.io/$PROJECT_ID/books-genai-jit']

  # Step 4: Push the Docker image to Google Cloud's Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/books-genai-jit']
  #gcloud services enable cloudbuild.googleapis.com
  #gcloud services enable artifactregistry.googleapis.com
  # gcloud builds submit --config=cloudbuild.yaml --substitutions=$PROJECT_ID="books-genai-tf-test"