management:
  endpoint:
    health:
      show-details: ALWAYS
  health:
    diskspace:  
      enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
spring:
  datasource:
    url: ${DB_URL}
    username: ${MY_USER}
    password: ${MY_PASSWORD}
  cloud:
    config:
      modelAnalysisName: ${MODEL_ANALYSIS_NAME}
      modelImageProName: ${MODEL_IMAGE_PRO_NAME}
      promptImage: ${PROMPT_IMAGE}