management:
  endpoint:
    health:
      show-details: ALWAYS
  health:
    diskspace:  
      enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
spring:
  datasource:
    url: ${DB_URL}
    username: ${MY_USER}
    password: ${MY_PASSWORD}
  cloud:
    config:
      modelAnalysisName: ${MODEL_ANALYSIS_NAME:text-bison-32k}
      modelImageProName: ${MODEL_IMAGE_PRO_NAME:text-bison-32k}
  ai:
    vertex:
      ai: 
        gemini:
          project-id: ${VERTEX_AI_GEMINI_PROJECT_ID}
          location: ${VERTEX_AI_GEMINI_LOCATION}
          chat: 
            options:
              model: gemini-pro
  threads:
    virtual: 
      enabled: true      

prompts:
  bookanalysis: ${PROMPT_BOOK_ANALYSIS:Extract the main ideas from the book The Jungle Book by Rudyard Kipling}
  promptImage: ${PROMPT_IMAGE:Extract the book name labels main color and author strictly in JSON format. The json output strictly have property names bookName mainColor author and labels.}
