FROM ubuntu:noble

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y --no-install-recommends tzdata ca-certificates git curl build-essential libfreetype6-dev libfontconfig-dev libcups2-dev libx11-dev libxext-dev libxrender-dev libxrandr-dev libxtst-dev libxt-dev libasound2-dev libffi-dev autoconf file unzip zip nano

RUN case $(uname -m) in \
        aarch64)   export BOOT_JDK_URL="https://download.bell-sw.com/java/23.0.1+13/bellsoft-jdk23.0.1+13-linux-aarch64.tar.gz" ;; \
        *)       export BOOT_JDK_URL="https://download.bell-sw.com/java/23.0.1+13/bellsoft-jdk23.0.1+13-linux-amd64.tar.gz" ;; \
    esac && \
    mkdir -p /opt/boot-jdk && \
    cd /opt/boot-jdk && \
    curl -L ${BOOT_JDK_URL} | tar zx --strip-components=1 && \
    test -f /opt/boot-jdk/bin/java && \
    test -f /opt/boot-jdk/bin/javac

RUN cd /opt && \
    git clone -b premain --depth 1 https://github.com/openjdk/leyden.git

RUN cd /opt/leyden && \
	bash configure --with-native-debug-symbols=none --with-boot-jdk=/opt/boot-jdk && \
	make images && \
	mv /opt/leyden/build/linux-$(uname -m)-server-release/images/jdk /opt

ENV JAVA_HOME /opt/jdk
ENV PATH $JAVA_HOME/bin:$PATH

COPY target/quotes-1.0.0.jar quotes-1.0.0.jar
RUN java -Djarmode=tools -jar /quotes-1.0.0.jar extract && \
    rm -rf /opt/jdk/demo && \
    rm -rf /opt/jdk/jmods

FROM ubuntu:noble
COPY --from=0 /opt/jdk /opt/jdk
COPY --from=0 /quotes-1.0.0 /quotes-1.0.0
ENV JAVA_HOME /opt/jdk
ENV PATH $JAVA_HOME/bin:$PATH

RUN java -XX:CacheDataStore=/application.cds -Dspring.aot.enabled=true -Dspring.context.exit=onRefresh -jar /quotes-1.0.0/quotes-1.0.0.jar
ENTRYPOINT ["java","-Dspring.aot.enabled=true","-XX:CacheDataStore=/application.cds","-jar","/quotes-1.0.0/quotes-1.0.0.jar"]