steps:
# restore Maven dependencies for faster builds
- id: 'download-cached-maven-dependencies'
  name: gcr.io/cloud-builders/gsutil
  entrypoint: bash
  volumes:
  - name: 'maven-repository'
    path: '/root/.m2'
  args:
  - '-c'
  - |
    gsutil cp gs://${PROJECT_ID}-cache-dependencies/cache/maven-dependencies.tgz maven-dependencies.tgz || exit 0
    tar -zxf maven-dependencies.tgz --directory / || exit 0

  # run tests first
- id: 'test'
  name: maven:3.9-eclipse-temurin-17
  entrypoint: mvn
  volumes:
  - name: 'maven-repository'
    path: '/root/.m2'
  args: ["verify"]

  # build service
- id: 'build-code'
  name: maven:3.9-eclipse-temurin-17
  entrypoint: mvn
  volumes:
  - name: 'maven-repository'
    path: '/root/.m2'
  args: [ "package", "-Dmaven.test.skip=true" ]

- id: 'build-project'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'gcr.io/$PROJECT_ID/quotes-docker', '-f', 'containerize/Dockerfile-fatjar']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/quotes-docker']

  # store Maven dependencies
- id: 'upload-cached-maven-dependencies'
  waitFor: [ 'build-project']
  name: gcr.io/cloud-builders/gsutil
  entrypoint: bash
  volumes:
  - name: 'maven-repository'
    path: '/root/.m2'
  args:
  - '-c'
  - |
    tar -zcf maven-dependencies.tgz /root/.m2
    gsutil cp maven-dependencies.tgz gs://${PROJECT_ID}-cache-dependencies/cache/maven-dependencies.tgz
images: ["gcr.io/$PROJECT_ID/quotes-docker"]